_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  antibot: 0
  automated_cron: 0
  block: 0
  block_content: 0
  breakpoint: 0
  cache_control_override: 0
  ckeditor5: 0
  config: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gin_toolbar: 0
  image: 0
  link: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  page_cache: 0
  path: 0
  path_alias: 0
  redirect: 0
  redirect_404: 0
  robotstxt: 0
  simple_sitemap: 0
  social_media_links: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  pathauto: 1
  views: 10
  minimal: 1000
theme:
  stark: 0
  bootstrap_barrio: 0
  sphereserver: 0
  claro: 0
  gin: 0
profile: minimal
