_core:
  default_config_hash: JqYNByWeXZGynyqoPRWQIjp3VcQhuoyq5WlM-7YzBvI
smtp_on: true
smtp_host: pmg.aira.cz
smtp_hostbackup: ''
smtp_port: '26'
smtp_protocol: standard
smtp_autotls: true
smtp_timeout: 30
smtp_username: ''
smtp_password: ''
smtp_from: admin@sphereserver.eu
smtp_fromname: 'SphereServer Website'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: true
smtp_test_address: ''
smtp_reroute_address: ''
smtp_debugging: false
smtp_debug_level: 1
prev_mail_system: php_mail
smtp_keepalive: false
