_core:
  default_config_hash: HlN7eAN2N4JIHsYv56V4E7sqC9bS609KwvGFjyD_mgk
langcode: en
uuid: aa01de8c-bacf-4fb3-b2c7-4605d50c6ad8
name: 'SphereServer X'
mail: admin@sphereserver.eu
slogan: 'Ultima Online game server, developed in C++'
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
